### ISSUE TITLE
Chrome detects it as a virus

### ISSUE THREAD

**Issue by omartayel** [henrikx/metroskininstaller#13]
![preview](https://user-images.githubusercontent.com/8867507/32003237-c3674dd2-b99e-11e7-90a4-279af5ac23e5.png)

**Comment by henrikx** [comment]
Thanks for filing the issue!
What AV do you use? I assure you this is a false positive, which is likely due to the program not being signed, and accesses the registry (required for automatic detection of steam dir). If you wish, you can look through the source code yourself and see that the software does not contain any viruses.

**Comment by omartayel** [comment]
I am using malwarebytes, but I think chrome itself detects it, and not malwarebytes

**Comment by henrikx** [comment]
Are you sure there are no other antivirus programs? When I download the same file on my own PC, it downloads fine. Maybe this is an issue with your set up and you should ignore the warning. Like I've said, if you're concerned about the program executing malicious code, feel free to look through the source code or even build it yourself. Try to download the latest release from here: https://github.com/henrikx/metroskininstaller/releases. What you've been trying to download is the full source, which may contain binaries not meant for release.

**Comment by henrikx** [comment]
You should see this site: https://productforums.google.com/forum/#!topic/chrome/r-9JQIboUmc. It seems like Chrome doesn't hesitate to flag nonmalicious files.

**Comment by omartayel** [comment]
I understand, was just reporting it in case you can do something to whitelist it

**Comment by henrikx** [comment]
I understand. Thank you. Unfortunately there's not really anything I can do at this point :/

**Comment by Xalaxis** [comment]
@henrikx Consider closing this perhaps?

**Comment by henrikx** [comment]
@Xalaxis Closing now :)
