### ISSUE TITLE
Save user's selected optional features

### ISSUE THREAD

**Issue by itay347** [henrikx/metroskininstaller#15]
Currently I save my preferred features in a separate text file.
The installer should have an option to "remember my preferences" (or just save automatically)

A good place to put the save file would be the skin's folder itself, I think.

**Comment by henrikx** [comment]
Due to how the installer dynamically looks for which extras can be installed, from RedSigma's manifest file, it is not simple, but I'll look at it when I finally have time to update this.

**Comment by henrikx** [comment]
Solved PR #21
