### ISSUE TITLE
Icons don't display correctly on Hi-DPI display

### ISSUE THREAD

**Issue by andritolion** [henrikx/metroskininstaller#16]
On a Hi-DPI display, like the one on the Surface Book 2, the icons don't display correctly and are somewhat distorted. Notice that in this picture, the three lines icon's lines are not all the same thickness.
![image](https://user-images.githubusercontent.com/34906030/40894570-7906cc6c-675f-11e8-92b9-5a9ff6d3ec9e.png)

**Comment by henrikx** [comment]
Hi. This is not a bug in the installer. Please file this bug in redsigma's repo
