### ISSUE TITLE
crashes on launch

### ISSUE THREAD

**Issue by azumukupoe** [henrikx/metroskininstaller#30]
Windows 11 Pro 22000.556

**Comment by PhantomGamers** [comment]
Post the crash log from Event Viewer under Windows Logs/Application

**Comment by azumukupoe** [comment]
my bad
seems to be a problem on my end...

**Comment by henrikx** [comment]
Hey @azumukupoe. Please let me know how you solved it. It is possible I could program something for the edge-case.

**Comment by azumukupoe** [comment]
it's kernelbase.dll error but I couldn't fix it because Windows in-place upgrade failed for me
