### ISSUE TITLE
Fullscreen issue

### ISSUE THREAD

**Issue by ChickenCranberry** [henrikx/metroskininstaller#34]
I have an issue with the Steam skin called "Metro for Steam" where whenever I go and open the Library tab, it'll go into full screen, leaving me without methods of exiting Library or Steam unless I close out on Windows or Task manager.

Here's a clip of the issue I'm currently facing.
![Screenshot (343)](https://user-images.githubusercontent.com/118373610/224490985-ca8639bc-95d1-4780-b7c9-fec0b7c913e7.png)
![Screenshot (344)](https://user-images.githubusercontent.com/118373610/224491047-ae61c0e3-8b7e-405c-b86c-f229e1216eab.png)

**Comment by redsigma** [comment]
Are you sure you're using the latest version of the installer ? I tested it myself and it works fine here.
https://github.com/henrikx/metroskininstaller/releases/tag/v1.4.16

**Comment by ChickenCranberry** [comment]
I had updated it but soon after I had seen that it was fixed or returned to normal and got on here to close this, it returned to being an issue once again.

**Comment by redsigma** [comment]
That's really weird. I am afraid I cant help you on that, but I recommend you to use the Patched version instead as that doesnt have this problem.

**Comment by ChickenCranberry** [comment]
Alright, I'll look and see if I could solve this issue with the Patched version like you said, thank you anyways for trying to help.
