### ISSUE TITLE
Change steam's icon on taskbar

### ISSUE THREAD

**Issue by 413x1nkp** [henrikx/metroskininstaller#35]
Just a little thought I had. wish that it would've looked like more like the installer one. Thank you for your great work anyway!
![image](https://user-images.githubusercontent.com/79400603/227855428-4003787c-2acd-4502-9ca1-fbfd949d61dd.png)

**Comment by henrikx** [comment]
Hey @alexlnkp!
This looks like it would be a great feature, but it is not really within the scope of what this installer is trying to do. If you have feature requests for the skin you can post them here https://github.com/redsigma/UPMetroSkin/issues.
