### ISSUE TITLE
If the latest release isn't 4.2.4 patch will be installed to the wrong directory

### ISSUE THREAD

**Issue by henrikx** [henrikx/metroskininstaller#7]

**Comment by PhantomGamers** [comment]
We could solve this by just installing to a "Metro" directory instead of putting the version number in the name.

Probably doesn't matter, not sure if it's even gonna get another official update but it would be an easy enough change.

**Comment by henrikx** [comment]
That's why I haven't solved this simple bug

**Comment by henrikx** [comment]
New official metro update makes this urgent
