### ISSUE TITLE
Installer loops installation

### ISSUE THREAD

**Issue by linuswillner** [henrikx/metroskininstaller#8]
There seems to be no proper installation termination outside of closing the program when the skin has been installed. Clicking Next just loops the installation process.

See this GIF for more info. (The GIF is a bit large and may take a while to load)

![Loop](http://images.lwtechgaming.me/Y8S7Hfr.gif)

**Comment by henrikx** [comment]
As of now the only indication of a successful install is the "All Done!" message. I'll fix this for the next release.

**Comment by henrikx** [comment]
Fixed now. Thanks for your feedback :)

**Comment by linuswillner** [comment]
No problem, glad I could lend a hand!
